data_ingestion:
  test_size: 0.2
  random_state: 2
  data_url: 
    https://raw.githubusercontent.com/sanskrutimahajan/ML_pipeline/refs/heads/main/spam.csv
  data_path: ./data
data_preprocessing:
  drop_columns:
  - 'Unnamed: 2'
  - 'Unnamed: 3'
  - 'Unnamed: 4'
  rename_columns:
    v1: target
    v2: text
feature_engineering:
  max_features: 3000
model_building:
  random_state: 42
  test_size: 0.2
  n_estimators: 100
model_evaluation:
  metrics:
  - accuracy
  - precision
  - recall
  - f1
